// Fotogramas del GIF «al pasar el cursor: activar / desactivar» (cursor real de puppeteer, dibujado luego). node cli/_gif_hover.mjs <dir>
import puppeteer from "puppeteer";
import { writeFileSync } from "node:fs";
const DIR = process.argv[2];
const URL = "https://giorgioburbanelli89.github.io/hekatan-struct-lineal/workspace/?t=muro-manabi&p=" + Buffer.from(JSON.stringify({ modelo: 1, cf: 1, L: 3, sCf: 1.5, ms: 0.3 })).toString("base64");
const nav = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--use-angle=swiftshader", "--enable-webgl"] });
const pag = await nav.newPage(); await pag.setViewport({ width: 1600, height: 1000 });
await pag.goto(URL, { waitUntil: "networkidle2", timeout: 120000 }); await new Promise((r) => setTimeout(r, 7000));
await pag.evaluate(() => { const p = window.__hekatanHoverPrefs; for (const k in p) p[k].val = true; });
const meta = []; let n = 0, cur = [1000, 700];
const foto = async (rotulo, clic = false, k = 1) => { for (let i = 0; i < k; i++) { const f = `f_${String(n++).padStart(3, "0")}.png`; await pag.screenshot({ path: `${DIR}/${f}` }); meta.push({ f, x: cur[0], y: cur[1], clic, rotulo }); } };
const ir = async (dest, rotulo, pasos = 8) => { const [x0, y0] = cur; for (let i = 1; i <= pasos; i++) { const t = i / pasos, e = t * t * (3 - 2 * t); cur = [x0 + (dest[0] - x0) * e, y0 + (dest[1] - y0) * e]; await pag.mouse.move(cur[0], cur[1]); await foto(rotulo); } };
const quieto = async (rotulo, ms, k) => { for (let i = 0; i < k; i++) { await pag.mouse.move(cur[0] + (i % 2), cur[1]); await new Promise((r) => setTimeout(r, ms)); await foto(rotulo); } };
const centro = (sel, txt) => pag.evaluate((sel, txt) => { const e = [...document.querySelectorAll(sel)].find((x) => x.innerText.trim().includes(txt)); if (!e) return null; e.scrollIntoView({ block: "center" }); const r = e.getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; }, sel, txt);
const casilla = (et) => pag.evaluate((et) => { const e = [...document.querySelectorAll(".tp-lblv")].find((x) => x.querySelector(".tp-lblv_l")?.innerText?.trim() === et); const r = e.querySelector("input").getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; }, et);
const clic = async (p, rotulo) => { await ir(p, rotulo, 7); await foto(rotulo, true, 2); await pag.mouse.click(p[0], p[1]); await new Promise((r) => setTimeout(r, 500)); await foto(rotulo, false, 2); };
// un punto sobre una CÁSCARA (no un nudo): se barre la pantalla y se mira qué dice el recuadro
const tipoEn = async (x, y) => { await pag.mouse.move(x, y); await new Promise((r) => setTimeout(r, 250));
  return pag.evaluate(() => { const d = [...document.querySelectorAll("div")].find((q) => q.style.whiteSpace === "pre-line" && q.style.display === "block"); return d ? d.textContent.split(/\s/)[0] : ""; }); };
let SOBRE = null;
for (let y = 420; y <= 720 && !SOBRE; y += 25) for (let x = 650; x <= 1050 && !SOBRE; x += 25) if ((await tipoEn(x, y)) === "Shell") SOBRE = [x, y];
console.log("punto sobre cáscara:", SOBRE);
await pag.mouse.move(20, 950); await new Promise((r) => setTimeout(r, 900));
const R1 = "ACTIVADO: al pasar el cursor salen el recuadro de resultados y la matriz K";
await ir(SOBRE, R1, 10); await quieto(R1, 400, 16);
const R2 = "Settings › Resultados › «🖱 Al pasar el cursor»";
await pag.mouse.move(20, 950); await new Promise((r) => setTimeout(r, 900));
await clic(await centro(".tp-fldv_t", "Al pasar el cursor"), R2.replace("🖱 ", ""));
const R3 = "Desactivo «info de nudos», «info de áreas» y «matriz K de áreas»";
await clic(await casilla("info de nudos"), R3); await clic(await casilla("info de áreas"), R3); await clic(await casilla("matriz K de áreas"), R3); await foto(R3, false, 4);
const R4 = "DESACTIVADO: el modelo queda limpio al pasar el cursor";
await ir(SOBRE, R4, 10); await quieto(R4, 350, 12);
const R5 = "Se vuelven a activar con las mismas casillas (nudos y barras, igual)";
await pag.mouse.move(20, 950); await new Promise((r) => setTimeout(r, 900));
await clic(await casilla("info de nudos"), R5); await clic(await casilla("info de áreas"), R5); await clic(await casilla("matriz K de áreas"), R5);
await ir(SOBRE, R5, 10); await quieto(R5, 350, 10);
writeFileSync(`${DIR}/meta.json`, JSON.stringify(meta), "utf-8");
console.log("fotogramas", n);
await nav.close();
