// Recorrido en el deploy PÚBLICO con un cursor visible: barra de menús, Análisis, Diseño de losa, DNE en Patrones de carga.
import puppeteer from "puppeteer";
const URL = "https://giorgioburbanelli89.github.io/hekatan-struct-lineal/workspace/?m=e3qQ74c6C2sEmWPq";
const OUT = "cli/shots/recorrido";
const nav = await puppeteer.launch({ headless: "new", executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", args: ["--no-sandbox","--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const p = await nav.newPage(); await p.setViewport({ width: 1400, height: 850 });
const dormir = ms => new Promise(r => setTimeout(r, ms)); let f = 0;
const foto = async (n = 1) => { for (let i = 0; i < n; i++) await p.screenshot({ path: `${OUT}/f${String(f++).padStart(3, "0")}.png` }); };
await p.goto(URL + "&v=" + Date.now(), { waitUntil: "networkidle2", timeout: 180000 }); await dormir(25000);
await p.evaluate(() => { const c = document.createElement("div"); c.id = "cur";
  c.style.cssText = "position:fixed;z-index:99999;width:28px;height:28px;pointer-events:none;left:700px;top:400px;filter:drop-shadow(1px 2px 2px rgba(0,0,0,.6))";
  c.innerHTML = '<svg viewBox="0 0 24 24" width="28" height="28"><path d="M3 2 L3 20 L8 15 L11.5 22 L14.5 20.6 L11 13.8 L18 13.8 Z" fill="#fff" stroke="#000" stroke-width="1.4" stroke-linejoin="round"/></svg>';
  const o = document.createElement("div"); o.id = "onda"; o.style.cssText = "position:fixed;z-index:99998;width:34px;height:34px;border-radius:50%;border:3px solid #ffd166;pointer-events:none;display:none;transform:translate(-50%,-50%)"; document.body.append(o);
  const t = document.createElement("div"); t.id = "rotulo"; t.style.cssText = "position:fixed;z-index:99999;left:50%;bottom:70px;transform:translateX(-50%);background:rgba(0,0,0,.8);color:#ffd166;font:bold 20px sans-serif;padding:8px 16px;border-radius:8px;pointer-events:none";
  document.body.append(c, t); });
const rotulo = t => p.evaluate(t => (document.getElementById("rotulo").textContent = t), t);
const ir = async (x, y, pasos = 6) => { const [x0, y0] = await p.evaluate(() => { const c = document.getElementById("cur"); return [parseFloat(c.style.left), parseFloat(c.style.top)]; });
  for (let i = 1; i <= pasos; i++) { await p.evaluate((x, y) => { const c = document.getElementById("cur"); c.style.left = x + "px"; c.style.top = y + "px"; }, x0 + (x - x0) * i / pasos, y0 + (y - y0) * i / pasos); await foto(); } };
const centro = sel => p.evaluate(sel => { const r = document.querySelector(sel).getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; }, sel);
const porTexto = async (sel, txt) => { await p.evaluate((sel, txt) => { [...document.querySelectorAll(sel)].find(e => e.textContent.includes(txt)).scrollIntoView({ block: "center" }); }, sel, txt); await dormir(400); await foto(2);
  return p.evaluate((sel, txt) => { const e = [...document.querySelectorAll(sel)].find(e => e.textContent.includes(txt)); const r = e.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; }, sel, txt); };
const clic = async (x, y) => { await ir(x, y);
  await p.evaluate((x, y) => { const o = document.getElementById("onda"); o.style.left = x + "px"; o.style.top = y + "px"; o.style.display = "block"; }, x, y); await foto(2);
  await p.mouse.click(x, y); await dormir(700);
  await p.evaluate(() => (document.getElementById("onda").style.display = "none")); await foto(3); };

await rotulo("Radier MOD_002 abierto con resultados (combinación DISEÑO)"); await foto(6);
await rotulo("Arriba, junto al nombre: Menú · Volver · Análisis · Diseño"); await foto(4);
await rotulo("▶ Análisis: estático, modal + animar"); await clic(...await centro("#hk-analisis-btn")); await foto(5);
await p.evaluate(() => document.getElementById("hk-analisis-menu")?.remove()); await dormir(300);
await rotulo("📐 Diseño: diseño de losa como SAFE"); await clic(...await centro("#hk-diseno-btn")); await foto(5);
await clic(...await centro('#hk-diseno-menu [data-id="franjas"]'));
await rotulo("Se diseña con la combinación DISEÑO (1.2D + 1.2DNE + 1.6L)"); await foto(5);
await p.evaluate(() => { const m = document.getElementById("hkf-met"); m.value = "fe"; m.onchange(); }); await dormir(300); await foto(2);
await rotulo("Calcular acero (elementos finitos)"); await clic(...await centro("#hkf-calc")); await dormir(3000); await rotulo("Resultado: varillas en mm, separación @ cm"); await foto(10);
await clic(...await centro("#hkf-x")); await dormir(500);
await rotulo("La sobrecarga muerta es CARGA: va en Patrones de carga"); await foto(3);
await clic(...await porTexto(".tp-fldv_b", "Patrones de carga")); await foto(2);
await clic(...await porTexto(".tp-btnv_b", "Sobrecarga muerta")); await rotulo("Asistente DNE con pesos NEC-15 (tabla y página)"); await foto(10);
await nav.close(); console.log("cuadros", f);
