import puppeteer from "puppeteer";
const [url, dir] = process.argv.slice(2);
const b = await puppeteer.launch({ headless: "new", protocolTimeout: 240000, args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage(); await p.setViewport({ width: 1600, height: 900 });
const log = []; p.on("console", m => log.push(m.text())); p.on("pageerror", e => log.push("PAGEERROR " + e.message));
await p.goto(url, { waitUntil: "domcontentloaded", timeout: 240000 });
for (let i = 0; i < 50 && !log.some(t => /Modal OK/.test(t)); i++) await new Promise(r => setTimeout(r, 3000));
await new Promise(r => setTimeout(r, 5000));
const firma = () => p.evaluate(() => { const v = [...document.querySelectorAll("div")].find(d => d.__ctx); let s = 0; v.__ctx.scene.traverse(o => { const a = o.geometry?.attributes?.position; if (a && o.visible && a.count < 20000) for (let i = 0; i < a.array.length; i += 7) s += a.array[i]; }); return +s.toFixed(3); });
const anima = async (tag) => { const a = await firma(); await new Promise(r => setTimeout(r, 400)); const c = await firma(); await p.screenshot({ path: `${dir}/rep_${tag}.png` }); const est = await p.evaluate(() => ({ case: [...document.querySelectorAll(".tp-lblv")].find(l => l.querySelector(".tp-lblv_l")?.textContent?.trim() === "Case results")?.querySelector("select")?.selectedOptions?.[0]?.textContent, animar: [...document.querySelectorAll(".tp-lblv")].find(l => /Animar/.test(l.querySelector(".tp-lblv_l")?.textContent || ""))?.querySelector("input")?.checked })); console.log(`${tag.padEnd(22)} anima=${a !== c}  case=${est.case}  animar=${est.animar}`); };
const elegir = (txt) => p.evaluate((t) => { const s = [...document.querySelectorAll(".tp-lblv")].find(l => l.querySelector(".tp-lblv_l")?.textContent?.trim() === "Case results")?.querySelector("select"); const o = [...s.options].find(o => o.textContent.trim().startsWith(t)); s.value = o.value; s.dispatchEvent(new Event("change", { bubbles: true })); }, txt);
const casilla = () => p.evaluate(() => [...document.querySelectorAll(".tp-lblv")].find(l => /Animar/.test(l.querySelector(".tp-lblv_l")?.textContent || "")).querySelector("input").click());
await anima("1_al_abrir");
await elegir("◈ Modo 2"); await new Promise(r => setTimeout(r, 2500)); await anima("2_modo2");
await elegir("Dead"); await new Promise(r => setTimeout(r, 3000)); await anima("3_dead");
await casilla(); await new Promise(r => setTimeout(r, 2000)); await anima("4_dead_animar");
await elegir("◈ Modo 1"); await new Promise(r => setTimeout(r, 2500)); await anima("5_modo1_animar");
await elegir("◈ Modo 3"); await new Promise(r => setTimeout(r, 2500)); await anima("6_modo3_animar");
console.log(log.filter(t => /PAGEERROR|animateMode|error/i.test(t)).slice(0, 6).join("\n"));
await b.close();
