import puppeteer from "puppeteer"; import fs from "node:fs"; import { createServer } from "http"; import { join, extname } from "path";
const raiz="C:/Users/j-b-j/Documents/Hekatan Calc 1.0.0/hekatan-struct-deploy/website/src/examples", BASE="/hekatan-struct-lineal/";
const MIME={".html":"text/html",".js":"text/javascript",".css":"text/css",".wasm":"application/wasm",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2"};
const srv=createServer((q,r)=>{let p=decodeURIComponent((q.url||"/").split("?")[0]);if(p.startsWith(BASE))p=p.slice(BASE.length-1);let f=join(raiz,p);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=join(f,"index.html");if(!fs.existsSync(f)){r.writeHead(404);return r.end("404");}r.writeHead(200,{"content-type":MIME[extname(f)]||"application/octet-stream"});r.end(fs.readFileSync(f));});
await new Promise(r=>srv.listen(4815,r));
const nav=await puppeteer.launch({headless:"new",executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",args:["--no-sandbox","--enable-unsafe-swiftshader","--use-angle=swiftshader","--enable-webgl"]});
const p=await nav.newPage(); await p.setViewport({width:1200,height:800});
const esp=m=>new Promise(r=>setTimeout(r,m));
await p.goto(`http://localhost:4815${BASE}workspace/?t=new-blank`,{waitUntil:"networkidle2",timeout:180000});
await p.waitForFunction(()=>!!document.querySelector("#viewer")?.__ctx,{timeout:120000}); await esp(6000);
const bot=()=>p.evaluate(()=>{const b=document.querySelector("#viewer").__ctx.controls.mouseButtons;
  const N={0:"ROTATE",1:"DOLLY",2:"PAN"}; return {LEFT:b.LEFT===null?"null":N[b.LEFT]??b.LEFT, MIDDLE:N[b.MIDDLE]??b.MIDDLE, RIGHT:N[b.RIGHT]??b.RIGHT};});
console.log("sin Shift :", JSON.stringify(await bot()));
await p.keyboard.down("Shift"); await esp(400);
console.log("con Shift (teclado real):", JSON.stringify(await bot()));
await p.keyboard.up("Shift"); await esp(200);
// y disparando el evento a mano: distingue «listener no registrado» de «evento no llega»
await p.evaluate(()=>window.dispatchEvent(new KeyboardEvent("keydown",{key:"Shift"})));
await esp(300);
console.log("con Shift (evento a mano):", JSON.stringify(await bot()));
await p.keyboard.up("Shift"); await esp(400);
console.log("tras soltar:", JSON.stringify(await bot()));
// ¿que pasa en un pointerdown REAL con Shift?
await p.evaluate(()=>{ window.__vistos=[]; const c=document.querySelector("#viewer canvas");
  c.addEventListener("pointerdown", e=>window.__vistos.push({btn:e.button, shift:e.shiftKey}), {capture:true}); });
await p.keyboard.down("Shift");
await p.mouse.move(600,400); await p.mouse.down({button:"middle"}); await esp(200);
console.log("botones DURANTE el arrastre con Shift:", JSON.stringify(await bot()));
await p.mouse.move(700,470,{steps:8}); await esp(200); await p.mouse.up({button:"middle"});
await p.keyboard.up("Shift"); await esp(300);
console.log("lo que vio el canvas:", JSON.stringify(await p.evaluate(()=>window.__vistos)));
console.log("enableRotate:", await p.evaluate(()=>document.querySelector("#viewer").__ctx.controls.enableRotate));
await nav.close(); srv.close();
