// Tarjetas con las FÓRMULAS en su casilla (barra y placa) y los dos botones: simbólica / numérica.
import puppeteer from "puppeteer";
import { mkdirSync } from "node:fs";
const i = process.argv.indexOf("--base"); const BASE = i >= 0 ? process.argv[i + 1] : "http://localhost:4600";
const DIR = "cli/shots/ctl_k_local_formulas"; mkdirSync(DIR, { recursive: true });
const espera = (ms) => new Promise((r) => setTimeout(r, ms));
const nav = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--enable-unsafe-swiftshader", "--use-angle=swiftshader", "--enable-webgl"] });
const pag = await nav.newPage(); await pag.setViewport({ width: 1600, height: 1000 });
const err = []; pag.on("pageerror", (e) => err.push(e.message));
let fallos = 0; const ok = (c, t) => { console.log(`${c ? "ok  " : "FALLA"} ${t}`); if (!c) fallos++; };
const abrir = async (id) => { await pag.goto(`${BASE}/workspace/index.html?t=${id}`, { waitUntil: "networkidle2", timeout: 180000 });
  await pag.waitForFunction(() => !!window.__hkKLocalHover && window.__hekatanStates?.elements?.val?.length, { timeout: 120000 }); await espera(4000); };
const recorte = async (n) => { const r = await pag.evaluate(() => { const b = document.getElementById("hk-klocal").getBoundingClientRect(); return [b.x, b.y, b.width, b.height]; });
  await pag.screenshot({ path: `${DIR}/${n}.png`, clip: { x: r[0], y: r[1], width: r[2], height: Math.min(r[3], 1000 - r[1]) } }); };
await abrir("plantillas");
const ib = await pag.evaluate(() => window.__hekatanStates.elements.val.findIndex((e) => e.length === 2));
await pag.evaluate((j) => { window.__hkKLocalHover.vista("letras"); window.__hkKLocalHover.ver(j, 40, 40); }, ib); await espera(600);
let t = await pag.evaluate(() => document.getElementById("hk-klocal").innerText);
await recorte("barra_letras");
ok(/12EI/.test(t.replace(/\s/g, "")) && /EA/.test(t) && /φ/.test(t), "barra «En letras»: fórmulas en las casillas (12EI…, EA/L, φ)");
ok(/Formulación simbólica/.test(t) && /Formulación numérica/.test(t), "barra: los dos botones");
const hb = await pag.evaluate((j) => { const h = window.__hkKLocalHover.hojasBarra(j); return h && { s: h.sim[1].length, n: h.num[1].length, sm: /12\*E\*I_33/.test(h.sim[1]), nm: /K_ii = \[\d/.test(h.num[1]) }; }, ib);
ok(hb && hb.sm && hb.nm, `barra: hoja simbólica con fórmulas (${hb?.s} car.) y numérica con números (${hb?.n} car.)`);
await abrir("estribo-puente");
const ip = await pag.evaluate(() => window.__hekatanStates.elements.val.findIndex((e) => e.length === 4));
await pag.evaluate((j) => { window.__hkKLocalHover.vista("letras"); window.__hkKLocalHover.verPano(j, 40, 30); }, ip); await espera(600);
t = await pag.evaluate(() => document.getElementById("hk-klocal").innerText);
await recorte("placa_letras");
ok(/D₀/.test(t) && /S·Nᵢ/.test(t) && /Allman/.test(t) && /K₁₂/.test(t), "placa «En letras»: bloque i–j con su fórmula en cada casilla y el mapa de bloques");
await pag.evaluate((j) => { window.__hkKLocalHover.vista("numeros"); window.__hkKLocalHover.verPano(j, 40, 30); }, ip); await espera(600);
await recorte("placa_numeros");
const hp = await pag.evaluate((j) => { const h = window.__hkKLocalHover.hojasPano(j); return h && { sm: /K_b11 = \[/.test(h.sim[1]), nm: /K_b_11 = \[/.test(h.num[1]) }; }, ip);
ok(hp && hp.sm && hp.nm, "placa: hoja simbólica por bloques de nudos y numérica con la matriz del solver");
ok(err.length === 0, "0 errores " + err.join(" | "));
await nav.close(); process.exit(fallos ? 1 : 0);
